#!/bin/bash

SCENARIO_N=5

mkdir simple-consumer/logs/scenario${SCENARIO_N}
# Consumer

GROUP_NAME="G1"
CONSUMER_ID=1
gradle simple-consumer:bootRun -Pargs=--spring.main.banner-mode=off,--spring.kafka.bootstrap-servers=10.11.1.111:9092,--spring.kafka.consumer.auto-offset-reset=latest,--asw.kafka.channel.in=asw.kafka.channel.beta,--asw.kafka.groupid=${GROUP_NAME},--logging.file.name=logs/scenario${SCENARIO_N}/consumer-${CONSUMER_ID}.log &
CONSUMER_ID=2
gradle simple-consumer:bootRun -Pargs=--spring.main.banner-mode=off,--spring.kafka.bootstrap-servers=10.11.1.111:9092,--spring.kafka.consumer.auto-offset-reset=latest,--asw.kafka.channel.in=asw.kafka.channel.beta,--asw.kafka.groupid=${GROUP_NAME},--logging.file.name=logs/scenario${SCENARIO_N}/consumer-${CONSUMER_ID}.log &

sleep 15

mkdir simple-producer/logs/scenario${SCENARIO_N}
# Producer

PRODUCER_ID=1
gradle simple-producer:bootRun -Pargs=--spring.main.banner-mode=off,--spring.kafka.bootstrap-servers=10.11.1.111:9092,--asw.kafka.channel.out=asw.kafka.channel.beta,--logging.file.name=logs/scenario${SCENARIO_N}/producer-${PRODUCER_ID}.log &
