# application.yml 
--- 
spring: 
  application: 
    name: sentence

server: 
#  port: ${PORT:${SERVER_PORT:0}}
  port: 8080

eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://eureka:8761/eureka/
# leave leaseRenewalIntervalInSeconds and leaseExpirationDurationInSeconds
# unchanged in production
# just here to provide quicker updates to Eureka for demos
  instance: 
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    metadataMap: 
      instanceId: ${spring.application.name}:${random.value}