version: '3'
services:
        zookeeper:
                image: wurstmeister/zookeeper
                ports:
                        - "2181:2181"
        kafka:
                image: wurstmeister/kafka:latest
                depends_on:
                        - "zookeeper"
                ports:
                        - "9092:9092"
                environment:
                        KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP:-10.11.1.111}
                        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
                        KAFKA_CREATE_TOPICS: "asw.kafka.channel.alpha:4:1,asw.kafka.channel.beta:4:1,asw.kafka.channel.gamma:4:1"
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock
